# Concatenando
### Por padrão, concat junta os DataFrames nas linhas e alinha as colunas automaticamente

In [6]:
import pandas as pd

df = pd.read_excel(r"C:\Users\caios\OneDrive\Desktop\Python para Excel\Cápitulo 5\Planilhas\course_participants.xlsx")

In [7]:
data=[[15, "Brazil", 4.1, "Bruno"],
      [44, "France", 6.1, "Becky"]]
more_users = pd.DataFrame(data=data,
                          columns=["age", "country", "score", "name"],
                          index=[1000, 1011])
more_users

      age country  score   name
1000   15  Brazil    4.1  Bruno
1011   44  France    6.1  Becky

In [8]:
# concat([DataFrames que serão concatenado], axis=0)
pd.concat([df, more_users], axis=0)

      Unnamed: 0   name  age  country  score continent
0         1001.0   Mark   55    Italy    4.5    Europe
1         1000.0   John   33      USA    6.7   America
2         1002.0    Tim   41      USA    3.9   America
3         1003.0  Jenny   12  Germany    9.0    Europe
1000         NaN  Bruno   15   Brazil    4.1       NaN
1011         NaN  Becky   44   France    6.1       NaN

In [ ]:
data=[[3, 4],
      [5, 6]]
more_categories = pd.DataFrame(columns=[])