# DADOS AUSENTES

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel(r"C:\Users\caios\OneDrive\Desktop\Python para Excel\Cápitulo 5\Planilhas\course_participants.xlsx")

In [5]:
df2 = df.copy() # cópia DataFrame original

In [6]:
df2.loc[1000, "score"] = None # Usando a forma Escalar um None a um célula especifica
df2.loc[1003, :] = None # None para todas as linhas do índice 1003
df2

      Unnamed: 0   name   age  country  score continent
0         1001.0   Mark  55.0    Italy    4.5    Europe
1         1000.0   John  33.0      USA    6.7   America
2         1002.0    Tim  41.0      USA    3.9   America
3         1003.0  Jenny  12.0  Germany    9.0    Europe
1000         NaN    NaN   NaN      NaN    NaN       NaN
1003         NaN   None   NaN     None    NaN      None

## Apagar linhas com dados ausentes com dropna()

In [7]:
df2.dropna()

   Unnamed: 0   name   age  country  score continent
0      1001.0   Mark  55.0    Italy    4.5    Europe
1      1000.0   John  33.0      USA    6.7   America
2      1002.0    Tim  41.0      USA    3.9   America
3      1003.0  Jenny  12.0  Germany    9.0    Europe

In [8]:
# remover apenas as linhas em todos os valores estão ausentes df.dropna(how="all")
df2.dropna(how="all")

   Unnamed: 0   name   age  country  score continent
0      1001.0   Mark  55.0    Italy    4.5    Europe
1      1000.0   John  33.0      USA    6.7   America
2      1002.0    Tim  41.0      USA    3.9   America
3      1003.0  Jenny  12.0  Germany    9.0    Europe

In [9]:
# obtendo um DataFrame ou Série booleana, dependendo se existe NaN ou não
# isna()
df2.isna()

      Unnamed: 0   name    age  country  score  continent
0          False  False  False    False  False      False
1          False  False  False    False  False      False
2          False  False  False    False  False      False
3          False  False  False    False  False      False
1000        True   True   True     True   True       True
1003        True   True   True     True   True       True

In [10]:
# para preenchar dados ausentes use fillna()
df2.fillna({"score": df2["score"].mean()})

      Unnamed: 0   name   age  country  score continent
0         1001.0   Mark  55.0    Italy  4.500    Europe
1         1000.0   John  33.0      USA  6.700   America
2         1002.0    Tim  41.0      USA  3.900   America
3         1003.0  Jenny  12.0  Germany  9.000    Europe
1000         NaN    NaN   NaN      NaN  6.025       NaN
1003         NaN   None   NaN     None  6.025      None