# Operadores Aritiméticos

In [27]:
import pandas as pd
import numpy as np

In [28]:
rainfall = pd.DataFrame(data={"City 1": [300.1, 100.2],
                              "City 2": [400.1, 500.3],
                              "City 3": [1000.5, 1100.6]})
# copiando original
rain_search = rainfall.copy()

more_rain = pd.DataFrame(data=[[100, 200], [300, 400]],
                         index=[1, 2],
                         columns=["City 1", "City 4"])

### Operador de adição usando add (+)

In [29]:
# use o fill=value para substituir os NaN 
rain_search.add(more_rain, fill_value=0)

   City 1  City 2  City 3  City 4
0   300.1   400.1  1000.5     NaN
1   200.2   500.3  1100.6   200.0
2   300.0     NaN     NaN   400.0

### Operador de subtração usando sub (-)

In [30]:
less_rain = more_rain.copy()
rain_search.sub(less_rain, fill_value=0)

   City 1  City 2  City 3  City 4
0   300.1   400.1  1000.5     NaN
1     0.2   500.3  1100.6  -200.0
2  -300.0     NaN     NaN  -400.0

### Operador de multiplicação usando mul (*)

In [31]:
df1 = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": [10, 20, 30, 40]
})

df2 = pd.DataFrame({
    "A": [5, np.nan, 7, 8],
    "B": [1, 2, np.nan, 4]
})

In [32]:
df1.mul(df2, fill_value=1)

      A      B
0   5.0   10.0
1   2.0   40.0
2  21.0   30.0
3  32.0  160.0

### Operação de divisão usando div (/)

In [33]:
df1.div(df2, fill_value=1)

          A     B
0  0.200000  10.0
1  2.000000  10.0
2  0.428571  30.0
3  0.500000  10.0

### Operação de potenciação usando pow (**)

In [34]:
df1.pow(df2)

         A          B
0      1.0       10.0
1      NaN      400.0
2   2187.0        NaN
3  65536.0  2560000.0