# DEFININDO DADOS

In [1]:
import pandas as pd

df = pd.read_excel(r"C:\Users\caios\OneDrive\Desktop\Python para Excel\Cápitulo 5\Planilhas\course_participants.xlsx")

df.index.name = "user_id"

In [2]:
# Copiar um DataFrame
df2 = df.copy()

df2.loc[1000, "name"] = "JOHN"
df2

         Unnamed: 0   name   age  country  score continent
user_id
0            1001.0   Mark  55.0    Italy    4.5    Europe
1            1000.0   John  33.0      USA    6.7   America
2            1002.0    Tim  41.0      USA    3.9   America
3            1003.0  Jenny  12.0  Germany    9.0    Europe
1000            NaN   JOHN   NaN      NaN    NaN       NaN

In [ ]:
# Alterar dados por índice
df2.loc[[1000, 1001], "score"] = [3, 4]
df2

KeyError: '[1001] not in index'

## Definindo dados indexação booleana

In [ ]:
tf = (df2["age"] < 20) | (df2["country"] == "USA")
df2.loc[tf, "name"] = "xxxx"
df2

         Unnamed: 0  name   age  country  score continent
user_id
0            1001.0  Mark  55.0    Italy    4.5    Europe
1            1000.0  xxxx  33.0      USA    6.7   America
2            1002.0  xxxx  41.0      USA    3.9   America
3            1003.0  xxxx  12.0  Germany    9.0    Europe
1000            NaN  JOHN   NaN      NaN    NaN       NaN

## Substituição de valores

In [ ]:
rainfall = pd.DataFrame(data={"City 1": [300.1, 100.2],
                              "City 2": [400.1, 500.3],
                              "City 3": [1000.5, 1100.6]})
# copiando original
rain_search = rainfall.copy()
# substituindo valor caso o valor seja true(verdadeiro)
rain_search[rain_search < 400] = 0

In [ ]:
# para substituir determinado valor em todo o DataFrame ou em colunas, use replace()
df2.replace("USA", "U.S.")
 
# para atuar em colunas especificas, dessa o replace funciona por meio de chave e valor 
# replace({"coluna": {"valor_antigo": "novo_valor"}})
df.replace({"country": {"USA": "U.S."}})

## Adicionando uma nova coluna

In [ ]:
# para adicionar uma nova coluna atribua os valores a uma nova coluna
# para adicionar uma nova coluna use um escalar ou uma lista
df.loc[:, "discount"] = 0
df.loc[:, "price"] = [46.5, 76.5, 99.5, 99.9]
df2

         Unnamed: 0   name   age  country  score continent
user_id
0            1001.0   Mark  55.0    Italy    4.5    Europe
1            1000.0   John  33.0      USA    6.7   America
2            1002.0    Tim  41.0      USA    3.9   America
3            1003.0  Jenny  12.0  Germany    9.0    Europe
1000            NaN   JOHN   NaN      NaN    NaN       NaN

In [ ]:
# calculos vetorizados, na adição de novas colunas
df2 = df.copy()
df2.loc[:, "birth year"] = 2021 - df2["age"]
df2

         Unnamed: 0   name  age  country  score continent  birth year
user_id
0              1001   Mark   55    Italy    4.5    Europe        1966
1              1000   John   33      USA    6.7   America        1988
2              1002    Tim   41      USA    3.9   America        1980
3              1003  Jenny   12  Germany    9.0    Europe        2009