In [74]:
import pandas as pd

In [75]:
df_planilha = pd.read_excel(r"C:\Users\caios\OneDrive\Desktop\Python para Excel\Cápitulo 5\Planilhas\course_participants.xlsx")

In [76]:
data = [["Mark", 55, "Italy", 4.5, "Europe"],
        ["John", 33, "USA", 6.7, "America"],
        ["Tim", 41, "USA", 3.9, "America"],
        ["Jenny", 12, "Germany", 9.0, "Europe"]]

df = pd.DataFrame(data=data,
                  columns=["name", "age", "country",
                           "score", "continent"],
                  index=[1001, 1000, 1002, 1003])
df

print(df)

# Várias Colunas / DataFrame 
# df.loc[:, ["country", "age"]]

       name  age  country  score continent
1001   Mark   55    Italy    4.5    Europe
1000   John   33      USA    6.7   America
1002    Tim   41      USA    3.9   America
1003  Jenny   12  Germany    9.0    Europe

# SELECIONANDO POR RÓTULO
### reordenar colunas com .loc[: ["colunas reodenadas..."]]
### : → seleciona todas as linhas. Porém os dois pontos (:) por último significam selecionar por colunas
### [ ... ] → define a ordem das colunas explicitamente.

In [77]:
colunas_reordenadas = df.loc[:,[ "continent", "country", "name", "age", "score"]]
print(colunas_reordenadas)

     continent  country   name  age  score
1001    Europe    Italy   Mark   55    4.5
1000   America      USA   John   33    6.7
1002   America      USA    Tim   41    3.9
1003    Europe  Germany  Jenny   12    9.0

In [78]:
# Valor Único / Tipo de dado retornado: escalar
tabela_pais = (df.loc[1000, "country"])

In [79]:
# Intervalo de colunas / DataFrame
df.loc[:, "name":"country"]

       name  age  country
1001   Mark   55    Italy
1000   John   33      USA
1002    Tim   41      USA
1003  Jenny   12  Germany

In [80]:
# Uma linha (1d) / Série
df.loc[1000, :]

name            John
age               33
country          USA
score            6.7
continent    America
Name: 1000, dtype: object

In [81]:
# Uma linha (2d) / DataFrame
df.loc[[1000], :]

      name  age country  score continent
1000  John   33     USA    6.7   America

In [82]:
# Várias linhas / DataFrame
df.loc[[1003, 1000], :]

       name  age  country  score continent
1003  Jenny   12  Germany    9.0    Europe
1000   John   33      USA    6.7   America

In [83]:
# Intervalo de linhas / DataFrame
df.loc[1000: 1002, :]

      name  age country  score continent
1000  John   33     USA    6.7   America
1002   Tim   41     USA    3.9   America

# FATIAMENTO DE RÓTULOS

In [84]:
# Usar escalares para a seleção de linha e coluna retorna um escalar
df.loc[1000, "name"]

'John'

In [85]:
#Usar um escalar na seleção de linha ou coluna retorna uma série
df.loc[[1000, 1002], "age"]

1000    33
1002    41
Name: age, dtype: int64

In [86]:
# Selecionar várias linhas e colunas retorna um DataFrame
df.loc[:1001, ["name", "country"]]

      name country
1001  Mark   Italy

# SELECINANDO POR POSIÇÃO
iloc = localização por índice
df.iloc[row_section, column_section]

In [87]:
df.iloc[0, 0] # Retorna um escalar

'Mark'

In [88]:
df.iloc[[0, 2], 1] # Retorna uma série

1001    55
1002    41
Name: age, dtype: int64

In [89]:
df.iloc[:3, [0, 2]] # Retorna um DataFrame

      name country
1001  Mark   Italy
1000  John     USA
1002   Tim     USA

# SELECIONANDO POR INDEXAÇÃO BOOLEANA

## and == & --- or == | --- not == ~

In [90]:
tf = (df_planilha["age"] > 40) & (df_planilha["country"] == "USA") # tf é uma Série com apenas True/False
df_planilha.loc[tf, :]

   Unnamed: 0 name  age country  score continent
2        1002  Tim   41     USA    3.9   America

In [91]:
# Se quiser filtar o índice, você pode se referir a ele como df.index
df.loc[df.index > 1001, :]

       name  age  country  score continent
1002    Tim   41      USA    3.9   America
1003  Jenny   12  Germany    9.0    Europe

## .isin()
### isin() serve para verificar se os valores de uma coluna ou Série estão contidos em uma lista (ou em outro objeto iterável).

In [92]:

df.loc[df["country"].isin(["Italy", "Germany"]), :]

       name  age  country  score continent
1001   Mark   55    Italy    4.5    Europe
1003  Jenny   12  Germany    9.0    Europe

## DataFrames com Base em Números
### caso algum número não corresponda com o critério retorna NaN(False) ou True caso corresponda

In [93]:
rainfall = pd.DataFrame(data={"City 1": [300.1, 100.2],
                              "City 2": [400.1, 500.3],
                              "City 3": [1000.5, 1100.6]})

In [94]:
rainfall > 400

   City 1  City 2  City 3
0   False    True    True
1   False    True    True

In [95]:
rainfall[rainfall < 400]

   City 1  City 2  City 3
0   300.1     NaN     NaN
1   100.2     NaN     NaN

# SELECIONANDO COM UM MULTIINDEX

In [98]:
# Um MultiIndex precisa ser ordenado
df_multi = df.reset_index().set_index(["continent", "country"])
df_multi = df_multi.sort_index()
df_multi

                   index   name  age  score
continent country
America   USA       1000   John   33    6.7
          USA       1002    Tim   41    3.9
Europe    Germany   1003  Jenny   12    9.0
          Italy     1001   Mark   55    4.5

In [ ]:
# Selecionado por Tupla (não esqueça dos parênteses )
df_multi.loc[("Europe", "Italy"), :]

                   index  name  age  score
continent country
Europe    Italy     1001  Mark   55    4.5

In [112]:
# Para redefinir uma parte de um MultiIndex forneça o nível como argumento
# Zero é a primeira coluna da esquerda
df_multi.reset_index(level=0)

        continent  index   name  age  score
country
USA       America   1000   John   33    6.7
USA       America   1002    Tim   41    3.9
Germany    Europe   1003  Jenny   12    9.0
Italy      Europe   1001   Mark   55    4.5